import type { MapEventPreset, MapEventPresetId } from "./mapEventTypes";

export const mapEventPresets: MapEventPreset[] = [
  {
    id: "locked_container_blue",
    name: "Locked Container Azul",
    description: "Spawna um container trancado azul em uma posição fixa. Requer setup permanente em types.xml e mapgroupproto.xml.",
    eventPrefix: "StaticContainerLockedBlue",
    defaultEventName: "StaticContainerLockedBlue",
    nominal: 1,
    min: 1,
    max: 0,
    lifetime: 2400,
    restock: 0,
    saferadius: 500,
    distanceradius: 500,
    cleanupradius: 250,
    deletable: true,
    initRandom: false,
    removeDamaged: false,
    position: "fixed",
    limit: "child",
    children: [
      { type: "Land_ContainerLocked_Blue_DE", min: 1, max: 1, lootmin: 5, lootmax: 9 },
    ],
    notes: [
      "Use uma coordenada plana e sem objetos próximos.",
      "O loot interno depende do mapgroupproto.xml e das usages no types.xml.",
    ],
  },
  {
    id: "locked_container_yellow",
    name: "Locked Container Amarelo",
    description: "Spawna um container trancado amarelo em uma posição fixa.",
    eventPrefix: "StaticContainerLockedYellow",
    defaultEventName: "StaticContainerLockedYellow",
    nominal: 1,
    min: 1,
    max: 0,
    lifetime: 2400,
    restock: 0,
    saferadius: 500,
    distanceradius: 500,
    cleanupradius: 250,
    deletable: true,
    initRandom: false,
    removeDamaged: false,
    position: "fixed",
    limit: "child",
    children: [
      { type: "Land_ContainerLocked_Yellow_DE", min: 1, max: 1, lootmin: 5, lootmax: 9 },
    ],
  },
  {
    id: "locked_container_mixed",
    name: "Locked Containers Azul + Amarelo",
    description: "Spawna até dois containers trancados no mesmo evento, um azul e um amarelo.",
    eventPrefix: "StaticContainerLockedMixed",
    defaultEventName: "StaticContainerLockedMixed",
    nominal: 2,
    min: 1,
    max: 0,
    lifetime: 2400,
    restock: 0,
    saferadius: 500,
    distanceradius: 500,
    cleanupradius: 250,
    deletable: true,
    initRandom: false,
    removeDamaged: false,
    position: "fixed",
    limit: "child",
    children: [
      { type: "Land_ContainerLocked_Blue_DE", min: 1, max: 1, lootmin: 5, lootmax: 9 },
      { type: "Land_ContainerLocked_Yellow_DE", min: 1, max: 1, lootmin: 5, lootmax: 9 },
    ],
  },
  {
    id: "shipping_key_blue",
    name: "Chave de Container Azul",
    description: "Spawna uma chave azul no chão para testes ou eventos controlados.",
    eventPrefix: "MapEvent_KeyBlue",
    defaultEventName: "StaticShippingContainerKeyBlue",
    nominal: 1,
    min: 1,
    max: 1,
    lifetime: 2400,
    restock: 0,
    saferadius: 5,
    distanceradius: 5,
    cleanupradius: 100,
    deletable: true,
    initRandom: false,
    removeDamaged: true,
    position: "fixed",
    limit: "child",
    children: [
      { type: "ShippingContainerKeys_Blue", min: 1, max: 1, lootmin: 1, lootmax: 1 },
    ],
  },
  {
    id: "shipping_key_yellow",
    name: "Chave de Container Amarela",
    description: "Spawna uma chave amarela no chão para testes ou eventos controlados.",
    eventPrefix: "MapEvent_KeyYellow",
    defaultEventName: "StaticShippingContainerKeyYellow",
    nominal: 1,
    min: 1,
    max: 1,
    lifetime: 2400,
    restock: 0,
    saferadius: 5,
    distanceradius: 5,
    cleanupradius: 100,
    deletable: true,
    initRandom: false,
    removeDamaged: true,
    position: "fixed",
    limit: "child",
    children: [
      { type: "ShippingContainerKeys_Yellow", min: 1, max: 1, lootmin: 1, lootmax: 1 },
    ],
  },
];

export function getMapEventPresets() {
  return mapEventPresets.map((preset) => ({ ...preset, children: preset.children.map((child) => ({ ...child })) }));
}

export function findMapEventPreset(presetId: string) {
  return mapEventPresets.find((preset) => preset.id === (presetId as MapEventPresetId)) || null;
}
