import { Router } from "express";
import { authenticateAdminUser, assignAdminUserServer, getAdminServerAccess, getAdminUserById } from "../lib/adminUsers";
import { clearAdminSessionCookie, createAdminSession, setAdminSessionCookie } from "../auth/adminSession";
import { buildManagedServerId, getManagedServerById, listManagedServers } from "../lib/serverRegistry";
import { createManagedOrganization, createManagedServerDraft, markManagedServerNitradoValidated, refreshManagedServerRegistryFromDb, saveOrganizationNitradoCredential, setManagedServerRuntimeEnabled } from "../lib/state";
import { discoverOrganizationNitradoServices, validateNitradoServiceSetup } from "../lib/serverIntegrations";
import { runManagedServerActivationPreflight } from "../lib/serverPreflight";
import { requestManagedServerRuntimeCycle } from "../lib/serverRuntimeCoordinator";
import { getOrganizationNitradoCredential } from "../lib/organizationIntegrations";

const router = Router();
const LEGACY_PANEL_COOKIE = "admin_panel_token";
function clearLegacyPanelCookie(res: any) { res.clearCookie(LEGACY_PANEL_COOKIE, { path: "/admin-panel", sameSite: "lax" }); res.clearCookie(LEGACY_PANEL_COOKIE, { path: "/", sameSite: "lax" }); }
function esc(value: unknown) { const entities: Record<string,string>={"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}; return String(value ?? "").replace(/[&<>\"']/g,c=>entities[c]||c); }
function orgIdFor(username: string) { return `org-${buildManagedServerId(username)}`; }
async function resolveManagedServer(serverId: unknown) { const sid=String(serverId||"").trim(); if(!sid)return undefined; let server=getManagedServerById(sid); if(server)return server; await refreshManagedServerRegistryFromDb(); return getManagedServerById(sid); }
function shell(content:string,title="ADM"){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>:root{color-scheme:dark;--bg:#090a0c;--surface:#111318;--border:#272b33;--text:#f7f7f8;--muted:#969da9}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#090a0c;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}.wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(480px,100%);background:#111318;border:1px solid var(--border);border-radius:24px;padding:32px}.brand{font-weight:900}.step{margin-top:28px;color:#7f8794;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{font-size:30px;line-height:1.08;margin:10px 0}p{color:var(--muted);line-height:1.55}.field{display:grid;gap:8px;margin:18px 0}.field label{font-size:13px;font-weight:700}.field input{width:100%;border:1px solid #303540;background:#0d0f13;color:#fff;border-radius:12px;padding:14px 15px;font:inherit}.button{width:100%;border:0;border-radius:12px;padding:14px 16px;margin-top:12px;background:#f5f5f5;color:#0a0b0d;font:inherit;font-weight:900;cursor:pointer}.button.secondary{background:#1b1e24;color:#fff;border:1px solid #303540;text-decoration:none;display:flex;justify-content:center}.error{margin-top:18px;padding:12px 14px;background:#2a1518;border:1px solid #5c252b;color:#ffb5bd;border-radius:12px}.progress{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:22px 0}.progress span{height:4px;border-radius:99px;background:#2a2e36}.progress span.on{background:#f3f3f3}.service{display:flex;gap:12px;align-items:flex-start;padding:14px;border:1px solid #303540;border-radius:14px;background:#0d0f13;margin:10px 0;cursor:pointer}.service input{margin-top:4px}.service strong{display:block}.service small{display:block;color:#8d95a2;margin-top:4px}.ok{margin:18px 0;padding:14px;background:#14231a;border:1px solid #285039;color:#b8efc8;border-radius:12px}</style></head><body><div class="wrap">${content}</div></body></html>`}
function loginPage(error=""){return shell(`<main class="card"><div class="brand">Advanced DayZ Management</div><div class="step">Admin</div><h1>Entre no seu painel</h1><p>Use o acesso administrativo criado para o seu servidor.</p><form method="post" action="/admin-panel/auth/login"><div class="field"><label>Usuário</label><input name="username" required autofocus></div><div class="field"><label>Senha</label><input name="password" type="password" required></div><button class="button">Entrar</button></form>${error?`<div class="error">${esc(error)}</div>`:""}</main>`,`Login · ADM`)}
function setupTokenPage(error=""){return shell(`<main class="card"><div class="brand">Advanced DayZ Management</div><div class="progress"><span class="on"></span><span></span></div><div class="step">Etapa 1 de 2</div><h1>Conecte sua Nitrado</h1><p>Informe seu token. O ADM encontra automaticamente os servidores DayZ disponíveis na sua conta.</p><form method="post" action="/admin-panel/setup/nitrado"><div class="field"><label>Token da Nitrado</label><input name="token" type="password" autocomplete="off" required></div><button class="button">Conectar Nitrado</button></form>${error?`<div class="error">${esc(error)}</div>`:""}</main>`,`Configurar servidor · ADM`)}
function setupServicesPage(services:any[],error=""){const cards=services.map(s=>`<label class="service"><input type="radio" name="serviceId" value="${esc(s.id)}" required><span><strong>${esc(s.name)}</strong><small>${esc([s.game,s.status].filter(Boolean).join(" · ")||"DayZ")}</small>${s.assignedServerName?`<small>Já reconhecido pelo ADM como ${esc(s.assignedServerName)}</small>`:""}</span></label>`).join("");return shell(`<main class="card"><div class="brand">Advanced DayZ Management</div><div class="progress"><span class="on"></span><span></span></div><div class="step">Etapa 1 de 2</div><h1>Selecione seu servidor</h1><p>Encontramos ${services.length} servidor${services.length===1?"":"es"} DayZ na sua conta Nitrado.</p>${services.length?`<form method="post" action="/admin-panel/setup/server">${cards}<button class="button">Continuar</button></form>`:`<div class="error">Nenhum servidor DayZ foi encontrado para este token.</div>`}<a class="button secondary" href="/admin-panel/setup">Usar outro token</a>${error?`<div class="error">${esc(error)}</div>`:""}</main>`,`Selecionar servidor · ADM`)}
function discordPage(serverId:string,connected=false,error=""){const server=getManagedServerById(serverId);return shell(`<main class="card"><div class="brand">Advanced DayZ Management</div><div class="progress"><span class="on"></span><span class="on"></span></div><div class="step">Etapa 2 de 2</div><h1>Conecte seu Discord</h1><p>Adicione o bot à comunidade do seu servidor.</p><div class="service"><span><strong>${esc(server?.name||serverId)}</strong></span></div>${connected||server?.integrations.discordGuildId?`<div class="ok">Discord conectado com sucesso.</div><a class="button secondary" href="/admin-panel">Ir para o painel</a>`:`<a class="button secondary" href="/api/auth/discord/connect?serverId=${encodeURIComponent(serverId)}&admin=1">Conectar Discord</a>`}${error?`<div class="error">${esc(error)}</div>`:""}</main>`,`Conectar Discord · ADM`)}

router.get("/login", async (req,res)=>{if(req.adminSession){const sid=req.adminSession.serverId;if(sid&&await resolveManagedServer(sid)){res.redirect("/admin-panel");return;}res.redirect("/admin-panel/setup");return;}res.type("html").send(loginPage(String(req.query.error||"")));});
router.post("/auth/login",async(req,res)=>{try{const user=await authenticateAdminUser(req.body?.username,req.body?.password);if(!user){res.status(401).type("html").send(loginPage("Usuário ou senha inválidos."));return;}clearLegacyPanelCookie(res);const server=user.serverId?await resolveManagedServer(user.serverId):undefined;const access=server?await getAdminServerAccess(user.id,server.id):null;const sid=server&&access&&access.organizationId===server.organizationId?server.id:null;setAdminSessionCookie(req,res,createAdminSession({adminUserId:user.id,username:user.username,serverId:sid}));res.redirect(sid?"/admin-panel":"/admin-panel/setup");}catch(e){res.status(503).type("html").send(loginPage(e instanceof Error?e.message:String(e)));}});
router.post("/auth/logout",(req,res)=>{clearAdminSessionCookie(req,res);clearLegacyPanelCookie(res);res.redirect("/admin-panel/login");});
router.get("/setup",async(req,res)=>{if(!req.adminSession){res.redirect("/admin-panel/login");return;}const fresh=await getAdminUserById(req.adminSession.adminUserId);if(!fresh){clearAdminSessionCookie(req,res);res.redirect("/admin-panel/login");return;}const resolved=fresh.serverId?await resolveManagedServer(fresh.serverId):undefined;const access=resolved?await getAdminServerAccess(fresh.id,resolved.id):null;const validServerId=resolved&&access&&access.organizationId===resolved.organizationId?resolved.id:null;if(validServerId!==req.adminSession.serverId)setAdminSessionCookie(req,res,createAdminSession({adminUserId:fresh.id,username:fresh.username,serverId:validServerId}));if(validServerId){res.type("html").send(discordPage(validServerId,req.query.discord==="connected",String(req.query.error||"")));return;}res.type("html").send(setupTokenPage(String(req.query.error||"")));});
router.post("/setup/nitrado",async(req,res)=>{if(!req.adminSession){res.redirect("/admin-panel/login");return;}try{const token=String(req.body?.token||"").trim();if(!token)throw new Error("Informe o token da Nitrado.");const oid=orgIdFor(req.adminSession.username);const org=await createManagedOrganization({id:oid,name:`${req.adminSession.username} Workspace`});if(!org)throw new Error("Não foi possível preparar seu workspace.");await saveOrganizationNitradoCredential(oid,token,{source:"admin-onboarding-discovery"});const result=await discoverOrganizationNitradoServices(oid);res.type("html").send(setupServicesPage(result.services));}catch(e){res.status(400).type("html").send(setupTokenPage(e instanceof Error?e.message:String(e)));}});
router.post("/setup/server",async(req,res)=>{if(!req.adminSession){res.redirect("/admin-panel/login");return;}try{const serviceId=String(req.body?.serviceId||"").trim();if(!/^\d+$/.test(serviceId))throw new Error("Selecione um servidor.");const oid=orgIdFor(req.adminSession.username);const credential=getOrganizationNitradoCredential(oid);if(!credential.token)throw new Error("Conecte sua conta Nitrado novamente.");const discovery=await discoverOrganizationNitradoServices(oid);const selected=discovery.services.find(s=>s.id===serviceId);if(!selected)throw new Error("Este servidor não está disponível para a conta Nitrado conectada.");let server=listManagedServers().find(s=>String(s.integrations.nitradoServiceId||"")===serviceId);if(server){const existingAccess=await getAdminServerAccess(req.adminSession.adminUserId,server.id);if(!existingAccess&&server.organizationId!==oid)throw new Error("Este servidor já pertence a outro workspace.");await saveOrganizationNitradoCredential(server.organizationId,credential.token,{source:"admin-onboarding-existing-server-recovery"});}else{const desiredId=buildManagedServerId(selected.name)||`dayz-${serviceId}`;server=getManagedServerById(desiredId);if(server&&String(server.integrations.nitradoServiceId||"")!==serviceId)server=undefined;if(!server){server=await createManagedServerDraft({id:desiredId,name:selected.name,organizationId:oid,nitradoServiceId:serviceId,nitradoBaseDir:selected.detectedBaseDir});}}if(!server)throw new Error("Não foi possível preparar o servidor selecionado.");if(!selected.assignedServerId){const validation=await validateNitradoServiceSetup(server.id,serviceId,selected.detectedBaseDir);server=await markManagedServerNitradoValidated(server.id,validation);}server=await resolveManagedServer(server.id)||server;if(!server.runtimeEnabled&&!server.runtime.activation?.lastDisabledAt){const preflight=await runManagedServerActivationPreflight(server.id);if(!preflight.passed)throw new Error("O servidor foi conectado, mas o runtime não passou nas verificações de isolamento. Revise o preflight antes de continuar.");server=await setManagedServerRuntimeEnabled(server.id,true);requestManagedServerRuntimeCycle(server.id,"activation");}const updated=await assignAdminUserServer(req.adminSession.adminUserId,server.id);if(!updated)throw new Error("Não foi possível vincular o admin ao servidor.");setAdminSessionCookie(req,res,createAdminSession({adminUserId:updated.id,username:updated.username,serverId:updated.serverId}));res.redirect("/admin-panel/setup");}catch(e){try{const result=await discoverOrganizationNitradoServices(orgIdFor(req.adminSession.username));res.status(400).type("html").send(setupServicesPage(result.services,e instanceof Error?e.message:String(e)));}catch{res.status(400).type("html").send(setupTokenPage(e instanceof Error?e.message:String(e)));}}});
export default router;
